#!/usr/bin/env bash
#
# Publish the CUPS queue over Bonjour so the M4 finds it with zero setup.
#
# CUPS already advertises shared queues via Avahi, but it does not always
# include the TXT records macOS looks at when deciding a printer is
# "driverless". This writes an explicit Avahi service file that spells them
# out, which is what makes the plotter show up in the Mac's printer list as
# a normal, ready-to-use printer instead of something wanting a driver.
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=/dev/null
source "$HERE/config.env"

QUEUE_NAME="${QUEUE_NAME:-DesignJet-T1200}"
QUEUE_DESC="${QUEUE_DESC:-HP DesignJet T1200ps}"
QUEUE_LOCATION="${QUEUE_LOCATION:-}"
ADVERTISE_URF="${ADVERTISE_URF:-no}"

# AVAHI_SERVICE_DIR is overridable so the generated XML can be inspected
# without touching the running system.
SERVICE="${AVAHI_SERVICE_DIR:-/etc/avahi/services}/${QUEUE_NAME}.service"
DRY_RUN="${DRY_RUN:-no}"

# Formats we genuinely accept. The Mac will pick application/pdf and send the
# job untouched; CUPS converts it to PostScript here on the Pi and streams
# that to the plotter. That conversion is the whole point -- it happens on
# the server, not on your Mac, so the Mac is free the moment the spool
# finishes.
PDL="application/pdf,application/postscript,image/jpeg,image/png,image/urf"

say() { printf '\033[1m==>\033[0m %s\n' "$*"; }

say "Writing $SERVICE"

{
cat <<XML
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<!-- Generated by scripts/make-airprint-service.sh : do not hand-edit. -->
<service-group>
  <name replace-wildcards="yes">${QUEUE_DESC} @ %h</name>
  <service>
    <type>_ipp._tcp</type>
    <subtype>_universal._sub._ipp._tcp</subtype>
    <port>631</port>
    <txt-record>txtvers=1</txt-record>
    <txt-record>qtotal=1</txt-record>
    <txt-record>rp=printers/${QUEUE_NAME}</txt-record>
    <txt-record>ty=${QUEUE_DESC}</txt-record>
    <txt-record>note=${QUEUE_LOCATION}</txt-record>
    <txt-record>product=(HP Designjet T1200ps)</txt-record>
    <txt-record>adminurl=http://%h.local:631/printers/${QUEUE_NAME}</txt-record>
    <txt-record>pdl=${PDL}</txt-record>
    <txt-record>Color=T</txt-record>
    <txt-record>Duplex=F</txt-record>
    <txt-record>Scan=F</txt-record>
    <txt-record>Fax=F</txt-record>
    <txt-record>PaperMax=isoC-A0</txt-record>
    <txt-record>Transparent=T</txt-record>
    <txt-record>Binary=T</txt-record>
    <txt-record>TLS=1.2</txt-record>
    <txt-record>printer-type=0x4901E</txt-record>
    <txt-record>printer-state=3</txt-record>
XML

# iOS/iPadOS insists on a URF record before it will offer a printer at all.
# Off by default because it makes the server claim a raster format it then
# has to convert; turn it on in config.env if you want to print from a phone
# or iPad and cups-filters is present to handle the conversion.
if [[ "$ADVERTISE_URF" == "yes" ]]; then
    echo "    <txt-record>URF=V1.4,CP1,PQ4,RS300-600,MT1-3-4-5-8,SRGB24,W8,DM1,IS1</txt-record>"
else
    echo "    <txt-record>URF=none</txt-record>"
fi

cat <<'XML'
  </service>
</service-group>
XML
} | { [[ "$DRY_RUN" == "yes" ]] && tee "$SERVICE" || sudo tee "$SERVICE" >/dev/null; }

if [[ "$DRY_RUN" == "yes" ]]; then
    say "DRY_RUN=yes -- wrote $SERVICE and stopped without touching Avahi"
    exit 0
fi

say "Reloading Avahi"
sudo systemctl restart avahi-daemon

sleep 2
if command -v avahi-browse >/dev/null 2>&1; then
    say "Bonjour now advertising:"
    timeout 5 avahi-browse -rt _ipp._tcp 2>/dev/null \
        | grep -A4 "$QUEUE_NAME" | sed 's/^/    /' || \
        echo "    (nothing yet -- give it a few seconds and re-check)"
fi

echo
echo "On the Mac mini M4 the plotter should now appear under"
echo "  System Settings > Printers & Scanners > Add Printer > Default"
echo "as: ${QUEUE_DESC} @ $(hostname)"
